baseURL: /
enableRobotsTXT: true
enableInlineShortcodes: true
module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.110.0
  imports:
    - path: github.com/google/docsy
      disable: false
      mounts: # https://github.com/google/docsy/discussions/1095
        # without mapping the mounts, Hugo can't find any of the theme files we override in the layouts directory
        # https://github.com/google/docsy/commit/215f68033bbc7bddf8dbec2bbabf8749d1998a17
        - source: assets
          target: assets
        - source: node_modules/bootstrap
          target: assets/vendor/bootstrap
        - source: node_modules/@fortawesome/fontawesome-free
          target: assets/vendor/Font-Awesome
        - source: i18n
          target: i18n
        - source: layouts
          target: layouts
        - source: static
          target: static
        - source: data
          target: data
        - source: node_modules/@fortawesome/fontawesome-free/webfonts
          target: static/webfonts
    - path: github.com/google/docsy/dependencies
      disable: false
  mounts:
    - source: content/en
      target: content

enableGitInfo: true
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango
permalinks:
  blog: "/:section/:year/:month/:day/:slug/"
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: UA-79996712-5
languages:
  en:
    description: >-
      Unlocking Innovation by Making Software Delivery Continuous, Scalable, and Safe
    languageName: English
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - name: CD-as-a-Service
      weight: 2
      url: /cd-as-a-service/
    - name: Armory CD
      weight: 3
      url: /continuous-deployment/
    - name: Scale Agent
      weight: 4
      url: /scale-agent/
    - name: Support
      weight: 5
      url: "https://support.armory.io/"
    - name: Blog
      weight: 6
      url: "https://www.armory.io/blog/"
    - name: Armory.io
      weight: 7
      url: "https://www.armory.io/"
    - name: Contribute
      weight: 10
      url: /contribute/
params:
  deploy-engine-plugin-version: 0.16.8
  armory-version: 2.28.x
  matching-oss-version-exact: 1.27.0
  mysql-version: 5.7; AWS Aurora
  postgresql-version: 10+
  armory-version-exact: 2.28.0
  halyard-armory-version: 1.12.1
  kubesvc-version: 1.0.33
  operator-extended-crd-version: v1alpha2
  operator-oss-crd-version: v1alpha2
  opa-server-version: 0.28.0
  copyright: Armory Inc.
  privacy_policy: "https://www.armory.io/privacy-policy/"
  terms_of_service: "https://www.armory.io/terms-of-service/"
  terms_and_conditions: "https://www.armory.io/terms-and-conditions/"
  cdaas_banner: false
  version_menu: Armory CD v2.28
  archived_version: false
  version: 2.28.0
  url_latest_version: "https://docs.armory.io/continuous-deployment/"
  github_repo: "https://github.com/armory/docs/"
  algolia_docsearch: false
  offlineSearch: true
  offlineSearchMaxResults: 50
  offlineSearchSummaryLength: 200
  prism_syntax_highlighting: true
  kubesvc-plugin:
    agent_plug_latest-3: 0.8.66
    agent_plug_latest_spin-3: 2.25.x (1.25.x)
    agent_plug_latest-2: 0.9.81
    agent_plug_latest_spin-2: 2.26.x (1.26.x)
    agent_plug_latest-1: 0.10.65
    agent_plug_latest_spin-1: 2.27.x (1.27.x)
    agent_plug_latest: 0.11.27
    agent_plug_latest_spin: 2.28.x (1.28.x)
  ui:
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_cache_limit: 10
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: true
    footer_about_disable: false
    feedback:
      enable: true
      "yes": Thank you for letting us know!
      "no": >-
        Sorry to hear that. Please <a
        href="https://github.com/armory/docs/issues/new">tell us how we can
        improve</a>.
    readingtime:
      enable: false
  mermaid:
    theme: forest
    enable: true
  links:
    user:
      - name: Email Armory
        url: "mailto:info@armory.io"
        icon: fa fa-envelope
        desc: Discussion and help from your fellow users
      - name: Twitter
        url: "https://twitter.com/cloudarmory"
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
      - name: RSS
        url: "https://docs.armory.io/index.xml"
        icon: fas fa-rss
        desc: Follow us on RSS to get the latest docs updates!
    developer:
      - name: GitHub
        url: "https://github.com/armory/docs/"
        icon: fab fa-github
        desc: Docs repository
      - name: Slack
        url: "https://join.spinnaker.io/"
        icon: fab fa-slack
        desc: Chat with Armory users and developers in the Spinnaker Slack
  versions:
    - version: Armory CD v2.27
      githubbranch: v2.27
      url: "https://v2-27.docs.armory.io/docs/"
    - version: Armory CD v2.26
      githubbranch: v2.26
      url: "https://v2-26.docs.armory.io/docs/"
